/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: ghostlyfail (https://sketchfab.com/ghostlyfail)
license: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
source: https://sketchfab.com/3d-models/low-poly-adventure-asset-pack-bda2fd1158df425fb703f53d926b1ec6
title: Low Poly Adventure Asset Pack
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";


export default function Adventure(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(
    "./models/low_poly_adventure_asset_pack.glb"
  );
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group
            name="4e65bb4247c24ae9829c43604374e9b7fbx"
            rotation={[Math.PI / 2, 0, 0]}
          >
            <group name="Object_2">
              <group name="RootNode">
                <group
                  name="Bush"
                  position={[-342, -28.41, -144.68]}
                  scale={[1.02, 1.17, 1.17]}
                >
                  <group name="Object_6">
                    <mesh
                      name="Bush_Material_#22_0"
                      castShadow
                      receiveShadow
                      geometry={nodes["Bush_Material_#22_0"].geometry}
                      material={materials.Material_22}
                    />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
};

useGLTF.preload("./models/low_poly_adventure_asset_pack.glb");
